# report_utils.py

from docx import Document
from docx.shared import Inches
from datetime import datetime


def generate_docx_report(report_text, output_path):
    doc = Document()

    # Title
    title = doc.add_heading('TenderLens AI Analysis Report', level=1)
    title.bold = True

    # Date
    date_para = doc.add_paragraph()
    date_para.add_run(
        f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}"
    ).italic = True

    doc.add_paragraph("")

    # Clean unwanted markdown symbols
    cleaned_text = (
        report_text
        .replace("###", "")
        .replace("##", "")
        .replace("**", "")
        .replace("```", "")
    )

    # Add content line by line
    for line in cleaned_text.split("\n"):

        line = line.strip()

        if not line:
            continue

        # Heading detection
        if line.endswith(":") or len(line) < 60:
            doc.add_heading(line, level=2)
        else:
            doc.add_paragraph(line)

    # Footer
    doc.add_page_break()

    footer_para = doc.add_paragraph()
    footer_para.add_run(
        "Generated by TenderLens AI"
    ).bold = True

    # Save document
    doc.save(output_path)
